/* eslint-disable max-len */
/**
 * Throne Support Knowledge Base
 *
 * Distilled from Throne's official support documentation at
 * https://support.thronescience.com so the StreamSync AI Support chat can
 * answer setup and troubleshooting questions with steps that match what
 * Throne themselves publish — instead of the plausible-but-unverified
 * placeholder content the integration demo shipped with.
 *
 * Refresh policy: this file is regenerated by `scripts/refresh-throne-prompt.ts`
 * (run quarterly, or whenever Throne updates a referenced article). Each
 * section carries the source URL so an iOS chat reply can cite the article
 * and the user can read the full version on Throne's site.
 *
 * IMPORTANT: do NOT inline the entire Throne knowledge base here. We pick
 * the SHORTEST distilled form of each article — enough that Claude can
 * answer common questions verbatim, but not so much that we bloat every
 * Anthropic call by 5-10k tokens. Long-form clarification still requires
 * the user to follow the link.
 */

export const THRONE_KNOWLEDGE_REFRESHED_ON = "2026-05-07";

export const THRONE_SUPPORT_KNOWLEDGE = `
## Throne Setup & Troubleshooting (sourced from support.thronescience.com — refreshed ${THRONE_KNOWLEDGE_REFRESHED_ON})

When the participant asks about setting up, pairing, or troubleshooting their Throne One, follow these procedures verbatim. They come from Throne's official docs. If a question goes beyond what's covered here, link the user to the relevant article URL below and offer to flag it for the research team.

### Account creation
The Throne app requires iOS 16+ or Android 14+. Tap "Create account" → enter email + password → verify email link → accept User Agreement + Privacy Policy. Source: https://support.thronescience.com/en/articles/12774385-how-to-create-a-throne-account

### Pairing the Throne One (first-time connect)
Preconditions: device plugged in and powered on, phone Bluetooth + Wi-Fi enabled, Throne app installed, Throne account created, device within 3–5 feet of phone.
1. Wait for the front light on the device to begin pulsing — this signals it's ready.
2. Open the Throne app and tap "Connect your Throne".
3. Press buttons 1 AND 2 simultaneously, holding for ~3 seconds, until the camera ring pulses blue.
4. The app auto-searches for the device; tap "Connect" when it appears.
5. Pick your home Wi-Fi network (Throne supports 2.4 GHz only during setup — pick the 2.4 GHz network if both bands are listed).
6. Enter Wi-Fi password → tap Connect → tap Continue.
7. If prompted, tap "Start update" for firmware. Keep the phone nearby and do NOT unplug during firmware update.
Source: https://support.thronescience.com/en/articles/12813831-step-1-connect-your-throne

### Bluetooth connection issues — Throne's official troubleshooting order
If pairing fails or the LED ring doesn't pulse blue, walk through these in order:
1. Confirm BOTH buttons are pressed at the EXACT same time (one-then-the-other doesn't trigger pairing).
2. Confirm the device has sufficient battery charge.
3. Confirm the LED ring is visible / lit when buttons are pressed.
4. Hold both buttons down for a full 3 seconds, not a quick tap.
5. Make sure pressure is truly simultaneous (a half-second offset between buttons is enough to fail pairing).
6. Restart the device by removing and remounting it on the toilet.
7. If none of the above work, contact Throne Support.
Source: https://support.thronescience.com/en/articles/12986974-troubleshooting-bluetooth-connection-issues

### Factory reset (last resort, removes pairing + Wi-Fi but preserves session history)
Warn the participant first: a factory reset CLEARS button assignments, removes the device from all user accounts, and erases pairing + Wi-Fi settings. It does NOT delete their account or past session history.
1. Locate Button 1 — near the camera housing.
2. Press and hold Button 1 continuously for ~15 seconds.
3. The red LEDs around the camera will fill the ring slowly.
4. Continue holding until the red ring pulses 3 times (~15 sec total). Once pulsing starts, the reset CANNOT be cancelled.
5. Release the button after the pulses complete.
6. To re-add the device: open Throne app → tap profile icon → "Add Device" under My Devices → follow onboarding.
Source: https://support.thronescience.com/en/articles/13317491-how-to-reset-your-throne-device

### LED state lookup — what the lights mean
Use this to interpret what the participant describes seeing:
- **Presence sensor green slow blink**: presence detected (someone near the device)
- **Presence sensor green slow blink + charging**: device awake AND charging with someone nearby
- **Presence sensor orange slow blink + charging**: charging without presence detected
- **Presence sensor solid green**: active session recording
- **Presence sensor green fading out**: session ending / wrapping up
- **Camera ring solid white**: session started
- **Camera ring white turns off**: session ended
- **Camera ring red flashes 3x (no session)**: button hasn't been assigned to a user (resolve via Throne app → button settings)
- **Camera ring red flashes 3x (during session)**: hardware malfunction — escalate to Throne support
- **Camera ring blue clockwise fill then pulsing**: pairing mode active
- **Camera ring red fills then pulses 3x**: factory reset in progress
Source: https://support.thronescience.com/en/articles/12884998-understanding-throne-one-led-indicators

### Hands-free mode (no button presses needed)
Throne One can auto-detect presence via Bluetooth + phone location signals and start/stop sessions without buttons. Prerequisites: device connected to Bluetooth + Wi-Fi, active Throne Membership, Throne app installed, location AND Bluetooth permissions granted in iPhone Settings. Sessions start when the user approaches; end when they walk away.
Source: https://support.thronescience.com/en/articles/12814840-step-3-use-throne-hands-free

### Notification settings (in Throne app, not StreamSync)
The Throne app has 4 toggles in its Settings → Notifications: Battery Low, Battery Full, Session Started, Session Finished. If a participant says they're not getting Throne notifications, point them at this menu first.
Source: https://support.thronescience.com/en/articles/12815325-how-to-adjust-your-throne-device-notification-settings

### Deleting an erroneous session in the Throne app
Open Throne app → navigate to the date containing the session → tap the session → tap the trash icon (top right) → confirm. Deletion is permanent; deleted sessions cannot be recovered.
Source: https://support.thronescience.com/en/articles/12986957-how-to-delete-a-session-in-the-throne-app

### When to escalate to Throne (vs. StreamSync research team)
Escalate to Throne support directly (in their app or via support.thronescience.com) when the issue is:
- Hardware malfunction (red LED flashes mid-session)
- Repeatable failure to pair after walking through the troubleshooting steps above
- Membership / billing questions
- Replacement device requests

Escalate to the StreamSync research team when the issue is:
- StreamSync app not seeing Throne data even though the Throne app does (data-sync-pipeline issue, not a Throne issue)
- Questions about the study, IPSS surveys, recovery instructions
- Help re-linking the participant's Throne account to their StreamSync email
`.trim();
